FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY Shared.Contracts/    Shared.Contracts/
COPY CoordinatorService/  CoordinatorService/

RUN dotnet publish CoordinatorService/CoordinatorService.csproj \
    -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "CoordinatorService.dll"]